# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
url:                   https://shikhabahirani.com

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# baseurl:               '/hydejack-starter-kit'


# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Shikha Bahirani | AI Expert, Applied Scientist, Machine Learning Engineer

# A short description (~150 chars) of the page used for the meta description tag.
description:           >
  AI and Applied Scientist transforming cutting-edge ML concepts into 
  high-impact business solutions across social media, finance, manufacturing and utilities sectors.

# A shorter description for the sidebar.
tagline:               Innovating AI for Business Impact

# A list of keywords for your blog
keywords:              [AI Solutions, Machine Learning, Data Science, Full-Stack AI, LLMs, 
                        Agentic Workflows, Stable Diffusion, Cross-Industry AI, FinTech AI, 
                        Social Media Analytics, Generative AI, AI Expert for hire, AI Expert consultant, AI consultant]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# logo:                  /assets/img/logo.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                Shikha Bahirani
  email:               shikhabahirani@gmail.com
  # Used by `jekyll-seo-tag`:
  twitter:             shikhabahirani
  linkedin:            https://www.linkedin.com/in/shikhabahirani/
  github:              https://github.com/shikhabahirani

# Add links to the sidebar.
menu:
  - title:             About
    url:               /about/
  # - title:             Expertise
  #   url:               /expertise/
  # - title:             Projects
  #   url:               /projects/
  # - title:             Blog
  #   url:               /blog/
  - title:             Contact
    url:               /contact/

# # Add links to the footer.
# legal:
#   - title:             Privacy Policy
#     url:               /privacy/
#   - title:             Terms of Service
#     url:               /terms/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2024 Shikha Bahirani. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /blog/:num/

# Theme
# theme: jekyll-theme-hydejack

# Customization
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
theme_color:           rgb(25,55,71)

# Google Fonts
google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
# google_analytics:      UA-XXXXXXXX-X

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
# disqus:                <disqus_shortname>

# Setting a tinyletter username will enable the newsletter subscription box.
# PRO version only!
# tinyletter:            <tinyletter_username>

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:         [about, newsletter, related, random]

  # Configure the order of complementary content on project pages
  project_addons:      [about, newsletter, other]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    false

  # Set to `true` if you don't want to use the auto-hiding (JavaScript based) navbar.
  no_navbar:           false

  # Set to true to disable the built-in search functionality.
  no_search:           false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  no_inline_css:       false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis. 
  no_page_style:       false

  # Set to `true` when building with the `--lsi` option
  use_lsi:             true

  # Set to `true` if you don't want to display the icon indicating external links
  no_mark_external:    false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  no_theme_color:      false

  # Disable the breadcrumbs above the title
  no_breadcrumbs:      false

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  cookies_banner:      false

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  advertise:           false

  # Buyers of the PRO version can opt to hide all dates from the theme.
  hide_dates:          false

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            false

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic:           true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true

# Collections
# ----------------------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true



# File inclusion/exclusion
# ----------------------------------------------------------------------------------------

exclude:
  - .jekyll-cache
  - .sass-cache
  - .ruby-lsp
  - .wrangler
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - functions
include:
  - _routes.json
  - .well-known
  - LICENSE.md


# Plugins
# ----------------------------------------------------------------------------------------

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at


# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
# google_site_verification: <verification-id>
# -- or --
# webmaster_verifications:
#   google:              <verification-id>
#   bing:                <verification-id>
#   alexa:               <verification-id>
#   yandex:              <verification-id>

# Used for twitter cards
# twitter:
#   username:            <username>

# Used for facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
# social:
#   name:                <firstname> <lastname>
#   links:
#     - https://twitter.com/<username>
#     - https://github.com/<username>


# Plugin Configs
# ---------------------------------------------------------------------------------------
optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!--", "-->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

# Jekyll Compose Defaults
# ---------------------------------------------------------------------------------------

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com
